# **Chapter 1: Data Types and Operators**

## Learning Objectives:


*   Identify data types (integer, strings, floats, boolean) in Python
* Understand how to convert between data types
*   Familiarize with operations of various data types in Python
*  Know how different data types interact

**Special Thanks to: **

These people have helped to create this learning package for python. 

1.   Darren, for organising the notes
2.   Sarah
3. Hakim
4. Chin Hong
5. Charlene

## 1.1 Data Types

In python, every "thing" is an object with a type. The four basic data types common across most languages are:

* Integers: 25 
* Floats : 25.1 (Decimals)
* Strings: 'apple' (demarcated by ' ' or " ")
* Boolean: True/False

### 1.1.1 Data Conversion/Typecasting

Certain functions in Python takes in only a particular data type, or outputs data of a particular type. Thus, it would be essential to know how data can be converted from one type to another. The common functions for converting are **str, int** and **float**

In [0]:
x=123; y='123'
print(str(x))
print(int(y))
print(float(y))

## 1.2 Operators (and Puntuators)

Operators can be thought of as tools (acting on something) that you use in conjunction with the various data types. Below are a list of some common operators you would come across in Python:

<img src ="https://drive.google.com/uc?id=1klpWVzvf6sTms7CJOylHDx-cGH_GsE4E">

These operators are usually mathematical and logical tools.

Punctuators, as the name suggest, functions pretty much like punctuation. Below are some common punctuators you would come across in Python:
 
<img src="https://drive.google.com/uc?id=1SnqCumWDvPwCwVtWjin8aYmW1g5fL3U_">

### 1.2.1 Assignment

Assignment refers to the process of storing data to a particular variable 

i.e. Variable Name = Data to be stored/assigned.  (right to left)

In this case the equal sign (=) simply seeks to separate the variable and the targeted data, and it helps indicate to the computer what data is to be stored, and under what variable. Refer to the appendix for more details on **Variable Syntax**

There are three common types of assignment in Python, **Single, Chained and Multiple**.

Single Assignment:

In [1]:
x=1
print(x)

1

Chained Assignment:

In [0]:
x=y=z=1
print(x)
print(y)
print(z)

Multiple Assignment: (Quite prevalent in Python)

In [0]:
x,y,z=1,2,3
print(x)
print(y)
print(z)

### 1.2.2 Arithematic Operators

* \+ **add** two operands of the **same data type**, i.e. **x+y**
* \- **subtract** right operand from left, i.e. **x-y**
* \* **multiply** two operands, i.e. **x*y**
* / **divide** left operand by the right one **(always results in a float)**, i.e. **x/y**
* // similarly divides left operand by the right, but **rounds down the resulting quotient**, i.e. **x//y**
* % **return the remainder** of the division left operand by the right, i.e. **x%y (remainder of x/y)**
* \*\* left operand **raised to the power** of the right, i.e. **x\*\*y**

In [2]:
x=5; y=3;z=-3
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x//y)
print(x//z)
print(x%y)
print(x**y)

8
2
15
1.6666666666666667
1
-2
2
125

The **operands can also be strings**, i.e. x='apple' and y='orange'.

In [0]:
x='apple'; y='orange'
print(x+y)
print(7*x)

As you can see, application of arithematic operators on strings are quite limited.
* +, add two operands of the **same type** (in this case, also known as **concatenation/joining**), i.e. 'apple'+'orange'='appleorange'
* \*, **repeats the base operand** (if you think about it * is just multiple +), i.e. integer * base_operand/string

### 1.2.3 Relational Operators

Commonly use to compare two sets of data (int, float, strings) and returns a Boolean, **True** or **False**

* ==, means **equal to**, e.g. x==y
* !=, means **not equal to**, e.g. x!=y
* <, means **less than**, e.g. x<y
* <=, means **less than or equal to**, e.g. x<=y
* \> , means **greater than**, e.g. x>y
* \>=, means **greater than or equal to**, e.g. x>=y

In [3]:
x=5; y=3;z=5
print(x==y)
print(x!=y)
print(x<y)
print(x<=y)
print(x>y)
print(x>=y)

False
True
False
False
True
True

What about strings? Can you compare between different data types. Lets see,

In [4]:
x=5; y='5'
print(x==y)
print(x!=y)

False
True

Lastly, note that when it comes to comparing between strings, they have a rather specific set of rules used for this comparison. Refer to the **appendix** for more details.

### 1.2.4 Logical Operators

Logical operators seek to connect/compare Boolean values and return another Boolean value as a result of the comparison

* and, **returns True if and only if both Boolean values are True**, i.e. True **and** True returns True
* or, **returns True if either Boolean value is True**, i.e. True or False, False **or** True, both returns True
* not, **flips the Boolean value**, i.e. **not** True returns False

You can refer to the table below if you are still confuse as to what and/or/not does.

<img src="https://drive.google.com/uc?id=13Q7Sl_EzM6rFXewmVGbueBQ_zPn6DbhH">

In [0]:
x=5; y=3
print((x<y) or not (x==y))
print((x<y) and not (x==y))
print((x<y) and (x==y))

True
False
False

## 1.3 Summary

To summarize, there are four main data types, int (integers), float (decimals), strings and boolean. Each data type can be acted upon by operators. In the case of arithmetic operators, they have the usual applications, and are more commonly operated on int and floats, and in certain instances, strings as well. Relational and logical operators both return Boolean values, which are useful when you are trying to control the flow of the code.

## 1.4 Appendix

###1.4.1 Variable Naming Syntax

* Must begin with a letter or underscore (_); cannot begin with a letter
* Case-sensitive; **A**pple is not the same as **a**pple
* May be of any length

Some common variable naming conventions:

* Capital letters usually reserved for Classes, i.e. class Animal, versus variable animal
* To improve readibility, a variable name consisting of multiple words are separted by underscores, i.e. this_is_a_variable
* Most importantly, create variable names that are sensible to not just you, but those whom you would be working with as well

### 1.4.2 String Comparison

* Both strings are compared starting from index 0 (beginning of the strings)
* The single characters at the current index of each strings are compared. 

> * If the characters are equal, increase the index by one and repeat the comparison. Else, the result of the comparison is returned

* If both strings are equal up to some point, then the longer string is greater, e.g. 'apples'>'apple'

In [0]:
print('abc'>'cba')
print('abd'>'abc')
print('apples'>'apple')